account/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from blogs import settings
from account import views as account_views
from account import forms as account_forms

app_name = 'account'

urlpatterns = [
    
    path('profile/', account_views.profile, name='profile'),
    path('wishlist/', account_views.wishlist_view, name='wishlist'),

    path('register/', account_views.register_view, name='register'),
    path('login/', account_views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='articles:index'), name='logout'),

    path('change-password/',
         auth_views.PasswordChangeView.as_view(
             template_name='account/change-password.html',
             success_url='/',
         ), name='change_password'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password-reset/password_reset.html',
             form_class=account_forms.CustomPasswordResetForm,
             email_template_name='account/password-reset/password_reset_email.html',
             success_url=reverse_lazy('account:password_reset_done',)
         ), name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password-reset/password_reset_done.html'
         ), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password-reset/password_reset_confirm.html',
             success_url=reverse_lazy('account:password_reset_complete')
         ), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password-reset/password_reset_complete.html',
         ), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

articles/urls.py
from django.conf.urls.static import static
from blogs import settings
from django.urls import path, include
from articles import views as article_views


app_name = 'articles'
urlpatterns = [
    path('', article_views.IndexPageView.as_view(), name='index'),
    path('category_results/<str:title>/', article_views.category_results.as_view(), name='category_results'),
    path('search', article_views.SearchView.as_view(), name='search_result'),
   
    path('read_more/<str:cate_title>/<str:title>', article_views.details, name='details'),
    path('fave/<str:title>', article_views.favourite_article, name='favourite_article'),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
     path('accounts/', include('account.urls')),

]

templates/base/layout/tools/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Bootstrap News Template - Free HTML Templates" name="keywords">
        <meta content="Bootstrap News Template - Free HTML Templates" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/favicon.ico' %}" rel="icon">

        <!-- Google Fonts -->
        <link href="{% static 'vendor/fonts/css/font.css' %}" rel="stylesheet"> 

        <!-- CSS Libraries -->
        <link href="{%static 'vendor/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/fontawesome/css/all.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css'%}" rel="stylesheet">
        <!-- <link href="{% static 'css/style2.css'%}" rel="stylesheet"> -->
    </head>

        <title>
            {% block site_title %}
        
            {% endblock %}
        </title>
        
        {% block base_css %}
        {% endblock %}
    
    </head>
    
    <body>

        {% block base_content %}
        {% endblock %}
    
      
    
    
        <script src="{% static 'vendor/jQuery/jquery-3.4.1.min.js' %}"></script>
        <script src="{%static 'vendor/bootstrap/bootstrap.bundle.min.js' %}"></script> <!-- i have it in vendor/bootstrap/dist/js/bootstrap.bundle.min.js -->
        <script src=" {% static 'lib/easing/easing.min.js' %}"></script> 
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>

    
        {% block base_js %}
        {% endblock %}
  
     </body>
  
  </html>


    

templates/base/layout/tools/footer.html
{% load i18n %}
{% load static %}        
        <!-- Footer Start -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Get in Touch</h3>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>123 News Street, NY, USA</p>
                                <p><i class="fa fa-envelope"></i>info@example.com</p>
                                <p><i class="fa fa-phone"></i>+123-456-7890</p>
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Useful Links</h3>
                            <ul>
                                <li><a href="#">Lorem ipsum</a></li>
                                <li><a href="#">Pellentesque</a></li>
                                <li><a href="#">Aenean vulputate</a></li>
                                <li><a href="#">Vestibulum sit amet</a></li>
                                <li><a href="#">Nam dignissim</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Quick Links</h3>
                            <ul>
                                <li><a href="#">Lorem ipsum</a></li>
                                <li><a href="#">Pellentesque</a></li>
                                <li><a href="#">Aenean vulputate</a></li>
                                <li><a href="#">Vestibulum sit amet</a></li>
                                <li><a href="#">Nam dignissim</a></li>
                            </ul>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Newsletter</h3>
                            <div class="newsletter">
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed porta dui. Class aptent taciti sociosqu
                                </p>
                                <form>
                                    <input class="form-control" type="email" placeholder="Your email here">
                                    <button class="btn">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Menu Start -->
        <div class="footer-menu">
            <div class="container">
                <div class="f-menu">
                    <a href="">Terms of use</a>
                    <a href="">Privacy policy</a>
                    <a href="">Cookies</a>
                    <a href="">Accessibility help</a>
                    <a href="">Advertise with us</a>
                    <a href="">Contact us</a>
                </div>
            </div>
        </div>
        <!-- Footer Menu End -->

        <!-- Footer Bottom Start -->

        <!-- Footer Bottom End -->

templates/base/layout/tools/header.html
{% load i18n %} 
{% load static %} 
{% if messages %} 
{% for message in messages%}
<div class="alert alert-{{message.tags}}" role="alert">{{ message }}</div>
{% endfor %} 
{% endif %}


<style type="text/css">
  #card1{
  position: relative;
  top:0px;
  left:500px;


   }
 </style>

<style type="text/css">
  #card2{
  position: relative;
  top:0px;
  left:200px;


   }
 </style>

<header class="box-shadow-sm">
  <!-- Top Bar Start -->
  <div class="top-bar">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="tb-contact">
            <p><i class="fas fa-envelope"></i>info@mail.com</p>
            <p><i class="fas fa-phone-alt"></i>+012 345 6789</p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="tb-menu">
            <a href="">About</a>
            <a href="">Privacy</a>
            <a href="">Terms</a>
            <a href="">Contact</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Top Bar Start -->

  <!-- Brand Start -->
  <div class="brand">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-3 col-md-4">
          <div class="b-logo">
            <a href="{% url 'articles:index' %}">
              <img src="{%static 'img/logo.png' %}" alt="Logo" />
            </a>
          </div>
        </div>
        
          
        <div class="col-lg-3 col-md-4">
          <form class=" form-inline md-form mr-auto mb-4 form-control-lg"
                        action="{% url 'articles:search_result' %}" method="GET">
          <div class="b-search">
            <input type="text" placeholder="Search"placeholder="Search" name='q' /> 
            <button type = 'submit'><i class="fa fa-search"></i></button>
          </div>
        </form>
        </div>
        
    <div id ='card1' class="card" style="width: 10rem;">
          <div class="card-body">
        

        {% if user.is_authenticated %}


        <div class="nav-item dropdown">
          <a
            href="#"
            class="nav-link dropdown-toggle"
            data-toggle="dropdown"
            ><small>Hello, {{ user.username }}</small></a
          >
          <div class="dropdown-menu">
            <a href="{% url 'account:profile' %}" class="dropdown-item">profile</a>
            <li class="dropdown-divider"></li>
            <a href="{% url 'account:change_password' %}" class="dropdown-item">Change password</a>
            <li class="dropdown-divider"></li>
            <a href="{% url 'account:logout' %}" class="dropdown-item">Logout</a>
          </div>
        </div>
       
        
         

        {% else %}
        <a class="navbar-tool ml-1 ml-lg-0 mr-n1 mr-lg-2" href="#signin-modal" data-toggle="modal">
            <div class="navbar-tool-icon-box">
                <i class="navbar-tool-icon fas fa-user"></i>
            </div>
            <div class="navbar-tool-text ml-n3">
                <small>Hello, Sign in</small>
            </div>
        </a>
        {% endif %}

            <!-- Dropdown menu links -->

            
          </div>
        </div>
        <div id ='card2' class="card" style="width: 8rem;">
          <div class="card-body">
        <a class="navbar-tool d-none d-lg-flex" href="{% url 'account:wishlist' %}"><span
          class="navbar-tool-tooltip">Favorite</span>
      <div class="navbar-tool-icon-box">
          <i class="navbar-tool-icon fas fa-heart"></i>
      </div>
        </a>

          </div>
        </div>
      </div>
    </div>
    
      </div>
      
    </div>
  </div>
  <!-- Brand End -->











  
                 
                  
  <!-- Nav Bar Start -->
  <div class="nav-bar">
    <div class="container">
      <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <a href="#" class="navbar-brand">MENU</a>
        <button
          type="button"
          class="navbar-toggler"
          data-toggle="collapse"
          data-target="#navbarCollapse"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div
          class="collapse navbar-collapse justify-content-between"
          id="navbarCollapse"
        >
          <div class="navbar-nav mr-auto">
            <a href="{% url 'articles:index' %}" class="nav-item nav-link active">Home</a>
            <div class="nav-item dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle"
                data-toggle="dropdown"
                >Categories list</a
              >
              <div class="dropdown-menu">
                {% for category in all_category%}
                
                <a href="{% url 'articles:category_results' title=category.title  %}" class="dropdown-item">{{category.title}}</a>
                {%endfor%}
              </div>
            </div>
         
            <a href="" class="nav-item nav-link">Contact Us</a>
          </div>
          
          <div class="social ml-auto">
            <a href=""><i class="fab fa-twitter"></i></a>
            <a href=""><i class="fab fa-facebook-f"></i></a>
            <a href=""><i class="fab fa-linkedin-in"></i></a>
            <a href=""><i class="fab fa-instagram"></i></a>
            <a href=""><i class="fab fa-youtube"></i></a>
      
          </div>
        </div>
      </nav>
    </div>
  </div>

</div>
</header>
{% include "components/login-register.html" %}
<!-- Nav Bar End -->