articles/urls.py
from django.conf.urls.static import static
from blogs import settings
from django.urls import path, include
from articles import views as article_views


app_name = 'articles'
urlpatterns = [
    path('', article_views.IndexPageView.as_view(), name='index'),
    path('category_results/<str:title>/', article_views.category_results.as_view(), name='category_results'),
    path('search', article_views.SearchView.as_view(), name='search_result'),
   
    path('read_more/<str:cate_title>/<str:title>', article_views.details, name='details'),
    path('fave/<str:title>', article_views.favourite_article, name='favourite_article'),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
     path('accounts/', include('account.urls')),

]

articles/models.py
from django.db import models
from account import models as account_models

class Category(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    category = models.ForeignKey(to= 'Category', on_delete=models.SET_NULL,blank=True,null=True)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to="Articles-Images", null=True, blank=True)
    likes =models.ManyToManyField(account_models.UserRegistration, related_name='like', blank=True)

    views = models.IntegerField(default=0)
    favorites = models.ManyToManyField(
        account_models.UserRegistration, related_name='favourite', blank=True)
    publish_date = models.DateField(auto_now_add=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, View, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib import messages
from articles import models as article_views
from django.urls import reverse, resolve
from django.http import JsonResponse
from django.db.models import Max, Min,Count
from django.contrib.auth.decorators import login_required

# Create your views here.




class IndexPageView(TemplateView):

    template_name = 'articles/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexPageView, self).get_context_data(**kwargs)
        most_viewed = article_views.Article.objects.order_by('-views')[:4]
        featured = article_views.Article.objects.order_by('-favorites')[:4]
        recent = article_views.Article.objects.order_by('-publish_date')[:4]
        most_recent = article_views.Article.objects.order_by('-update_at')[:4]
        context = {
    
        'most_viewed' : most_viewed,
        'featured' : featured,
        'recent' : recent,
        'most_recent':most_recent,
        }
        context.update(needed_everywhere())
        return context


def needed_everywhere():
    context = {}
    all_articles = {}
    all_categories = article_views.Category.objects.all()
 

    for category in all_categories:
        all_articles[category.title] = article_views.Article.objects.filter(
            category__title=category.title).order_by('-create_at')[:12]

  
    context['all_category'] = all_categories
    context['all_articles'] = all_articles

 
    

    return context

# def category_results(request,category_title):
#     return render(request,'articles/list_category.html')



class category_results(ListView):

    template_name = 'articles/list_category.html'
    model = article_views.Article
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super(category_results, self).get_context_data(**kwargs)
        category_title = self.kwargs.get('title')
        articles = article_views.Article.objects.filter(category__title=  category_title) 

        most_viewed = article_views.Article.objects.order_by('-views')[:4]
        featured = article_views.Article.objects.order_by('-favorites')[:4]
        recent = article_views.Article.objects.order_by('-publish_date')[:4]
        cate_list = article_views.Category.objects.values('title').annotate(count = Count('article'))
        category  = {cate['title']:cate['count'] for cate in cate_list}  

      

        paginator = Paginator(articles, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            articles_files = paginator.page(page)
        except PageNotAnInteger:
            articles_files = paginator.page(1)
        except EmptyPage:
            articles_files = paginator.page(paginator.num_pages)

      
       
        context = {
        'articles' :articles_files,
        'in_this_category' : article_views.Article.objects.filter(category__title__iexact=category_title)[:4],
        'most_viewed' : most_viewed,
        'featured' : featured,
        'recent' : recent,
        'category_title': category_title,
        'cate_list': category,}
        context.update(needed_everywhere())
        return context



class SearchView(ListView):

    template_name = 'articles/list_category.html'
    model = article_views.Article
    paginate_by = 4
    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        search_term = self.request.GET.get('q').strip(' */%^$#@!?')
        articles = article_views.Article.objects.filter(Q(title__icontains=search_term) | Q(
            author__icontains=search_term) | Q(category__title__icontains=search_term) | Q(description__icontains=search_term))
        article_number = articles.count()
        current_url = resolve(self.request.path_info).url_name
        most_viewed = article_views.Article.objects.order_by('-views')[:4]
        featured = article_views.Article.objects.order_by('-favorites')[:4]
        recent = article_views.Article.objects.order_by('-publish_date')[:4]
        cate_list = article_views.Category.objects.values('title').annotate(count = Count('article'))
        category  = {cate['title']:cate['count'] for cate in cate_list}
      


        paginator = Paginator(articles, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            articles_files = paginator.page(page)
        except PageNotAnInteger:
            articles_files = paginator.page(1)
        except EmptyPage:
            articles_files = paginator.page(paginator.num_pages)
            
        
        context = {
            'articles': articles_files,
            'in_this_category' : article_views.Article.objects.order_by('-update_at')[:6],
            'most_viewed' : most_viewed,
            'featured' : featured,
            'recent' : recent,
            'products_number': article_number,
            'search': search_term,
            'url_name': current_url,
            'search_exist': 'true',
            'cate_list': category,
        }
      
        context.update(needed_everywhere())
        return context


def details(request,cate_title,title):
    article =  article_views.Article.objects.get(title__iexact=title)
    article.views +=1
    article.save()
    most_viewed = article_views.Article.objects.order_by('-views')[:4]
    featured = article_views.Article.objects.order_by('-favorites')[:4]
    recent = article_views.Article.objects.order_by('-publish_date')[:4]
    cate_list = article_views.Category.objects.values('title').annotate(count = Count('article'))
    category  = {cate['title']:cate['count'] for cate in cate_list}
  
    context = {
        'article_title': article.title,
        'article_cate': article.category.title,
        'aricle_image' : article.image,
        'article_views': article.views,
        'artcile_likes': article.likes.count(),
        'description' : article.description,
        'author' : article.author,
        'date' : article.publish_date,
        'in_this_category' : article_views.Article.objects.filter(category__title__iexact=cate_title)[:4],
        'most_viewed' : most_viewed,
        'featured' : featured,
        'recent' : recent,
        'cate_list': category,
        'article': article,
        }
   
    context.update(needed_everywhere())
    return render (request, 'articles/single-page.html', context)




@ login_required(login_url='/accounts/login/')
def favourite_article(request,title):

    url = request.META.get('HTTP_REFERER')
    article = get_object_or_404(article_views.Article, title=title)
    if article.favorites.filter(id=request.user.id).exists():
        article.favorites.remove(request.user)
        messages.warning(
            request, f'"{article.title}" has been removed from your Favorites.')
    else:
        article.favorites.add(request.user)
        messages.success(
            request, f'"{article.title}" has been added to your Favorite.')
    return HttpResponseRedirect(url)



    

templates/articles/list_category.html
{% extends "base/main/layout/layout.html" %}
{% load i18n %}
{% load static %}

{% block site_title %}
Category's blogs
{% endblock %}

{% block content %}



<style type="text/css">
    .topcornerright{
    position:relative ;
    top:-300px;
    left:1000px;

 
     }
   </style>

<style type="text/css">
#category_header:after {
    content: "";
    display: block;
    width: 900px;
    height: 2px;
    background: rgb(240, 103, 103);
    left: 0;
    top: 50%;
    position: relative;
  }

</style>

  

<div class="col-md-6">
    {%if search %}
    <h2 id='category_header'><span class="badge badge-dark">search on :...</span> {{search}}</h2>
    
    <div class="row cn-slider slick-initialized slick-slider">
    {%else%}
    <h2 id='category_header'>{{category_title}}</h2>
    
    <div class="row cn-slider slick-initialized slick-slider">
    {%endif%}
<!-- end meta -->
</div><!-- end blog-box -->
</div>





 


<div class="col-lg-9 col-md-12 col-sm-12 col-xs-12" style = 'padding-right: 150px;'>





    <div class="page-wrapper">
     
        <div class="blog-list clearfix">
          
        {% for article in articles %}
            <div class="blog-box row">
                <div class="col-md-4">
                    
                    <div class="post-media">
                        <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}" title="">
                            <img src="/media/{{ article.image }}" alt="" class="img-fluid">
                            <div class="hovereffect"></div>
                        </a>
                    </div><!-- end media -->
                </div><!-- end col -->
              
                <div class="blog-meta big-meta col-md-8">
                    <h4><a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}" title="">{{article.title}}</a></h4>
                    <p>{{article.description|truncatewords:10 }}</p>
                    <small class="badge badge-info"><a class="bg-black" href="{% url 'articles:category_results' title=article.category.title  %}" title="">{{article.category.title}}</a></small>
                    <small>  {{article.publish_date}}</small>
                    <small> {{article.author}}</small>
                    <small><i class="fa fa-eye"></i> {{article.views}}</small>
                    {% if user in article.favorites.all %}
                    <a class="btn-wishlist btn-sm"
                        href="{% url 'articles:favourite_article' article.title %}" data-toggle="tooltip"
                        data-placement="left" data-original-title="Remove from favorite">
                        <i class="fa fa-heart"></i></a>
                    {% else %}
                    <a class="btn-wishlist btn-sm"
                        href="{% url 'articles:favourite_article' article.title %}" data-toggle="tooltip"
                        data-placement="left" data-original-title="Add to favorite"> 
                        <i class="fas fa-heart-broken"></i></a>
                    {% endif %}
                </div><!-- end meta -->
            </div><!-- end blog-box -->

            <hr class="invis">
        {%endfor%}
    </div>
    
    <hr class="invis">
    <div class="pagination">
        <span class="step-links">
            {% if articles.has_previous %}
                <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page=1">&laquo; first</a>
                <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ articles.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
            </span>
    
            {% if articles.has_next %}
                <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ articles.next_page_number }}">next</a>
                <a href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ articles.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>




</div>
<div class="topcornerright" >
    <div class="sidebar-widget" >
     
            
    {% include "components/left_slider.html" %}
      
       <!-- end sidebar -->
    </div>
</div> 

</div>  


{% endblock %}

templates/articles/single-page.html
{% extends "base/main/layout/layout.html" %}
{% load i18n %}
{% load static %}

{% block site_title %}
{{articles.title}}
{% endblock %}

{% block content %}
        
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'articles:index' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'articles:category_results' title=article_cate  %}">{{article_cate}}</a></li>
                    <li class="breadcrumb-item active">{{article_title|truncatewords:10}}</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        <!-- Single News Start-->
        <div class="single-news">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="sn-container">
                            <div class="sn-img">
                                
                                <img src="/media/{{ aricle_image }}" />
                            </div>
                            
                            {% if user in article.favorites.all %}
                            <a class="btn-wishlist btn-sm"
                                href="{% url 'articles:favourite_article' article.title %}" data-toggle="tooltip"
                                data-placement="left" data-original-title="Remove from favorite">
                                <i class="fa fa-heart fa-2x"></i>Remove to favorite</a>
                            {% else %}
                            <a class="btn-wishlist btn-sm"
                                href="{% url 'articles:favourite_article' article.title %}" data-toggle="tooltip"
                                data-placement="left" data-original-title="Add to favorite"> 
                                <i class="fas fa-heart-broken fa-2x"></i>Add to favorite</a>
                            {% endif %}
                            <div class="sn-content">
                                <h1 class="sn-title">{{article_title}}</h1>
                                <p>
                                   {{description}}
                                </p>
                           
                            </div>
                        </div>
                        <div class="sn-related">
                            <h2>Related News</h2>
                            <div class="row sn-slider">
                                {% for article in in_this_category|slice:'2:' %}
                                <div class="col-md-4">
                                    <div class="sn-img">
                                        <img src="/media/{{ article.image }}" />
                                        <div class="sn-title">
                                            <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{ article.title }}/a>
                                        </div>
                                    </div>
                                </div>
                                {%endfor%}
                                {% for article in in_this_category|slice:':2' %}
                                <div class="col-md-4">
                                    <div class="sn-img">
                                        <img src="/media/{{ article.image }}" />
                                        <div class="sn-title">
                                            <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{ article.title }}/a>
                                        </div>
                                    </div>
                                </div>
                                {%endfor%}
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-4">
                        <div class="sidebar">
                            <div class="sidebar-widget">
                                <h2 class="sw-title">In This Category</h2>
                                <div class="news-list">
                                    {% for article in in_this_category %}
                                    <div class="nl-item">
                                        <div class="nl-img">
                                            <img src="/media/{{ article.image }}" />
                                        </div>
                                        <div class="nl-title">
                                            <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{ article.title }}</a>
                                        </div>
                                    </div>
                                    {%endfor%}
                                </div>
                            </div>
                            
                         
                            <div class="sidebar-widget">
                                <div class="tab-news">
                                    <ul class="nav nav-pills nav-justified">
                                        <li class="nav-item">
                                            <a class="nav-link active" data-toggle="pill" href="#featured">Featured</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" data-toggle="pill" href="#popular">Popular</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" data-toggle="pill" href="#latest">Latest</a>
                                        </li>
                                    </ul>

                                    <div class="tab-content">
                                        <div id="featured" class="container tab-pane active">
                                        {% for article in featured %}
                                            <div class="tn-news">
                                                <div class="tn-img">
                                                    <img src="/media/{{ article.image }}" />
                                                </div>
                                                <div class="tn-title">
                                                    <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{ article.title }}</a>
                                                </div>
                                            </div>
                                            {%endfor %}
                                        </div>


                                        <div id="popular" class="container tab-pane fade">
                                            {% for article in most_viewed%}
                                            <div class="tn-news">
                                                <div class="tn-img">
                                                    <img src="/media/{{ article.image }}" />
                                                </div>
                                                <div class="tn-title">
                                                    <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{article.title}}</a>
                                                </div>
                                            </div>
                                           {%endfor%}
                                        
                                        </div>
                                        <div id="latest" class="container tab-pane fade">
                                            {% for article in recent%}
                                            <div class="tn-news">
                                                <div class="tn-img">
                                                    <img src="/media/{{ article.image }}" />
                                                </div>
                                                <div class="tn-title">
                                                    <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{article.title}}</a>
                                                </div>
                                            </div>
                                           {%endfor%}
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                           

                            <div class="sidebar-widget">
                                <h2 class="sw-title">Category List</h2>
                                <div class="category">
                                    {% for title,count in cate_list.items %}
                                   
                                    <ul> 
                                        <li><a href="{% url 'articles:category_results' title=title  %}">{{title}}</a><span>{{count}}</span></li>
                                       
                                    </ul>
                                    {%endfor%}
                               
                                </div>
                            </div>

                           
                            
                            <div class="sidebar-widget">
                                <h2 class="sw-title">Tags Cloud</h2>
                                <div class="tags">
                                    <a href="">National</a>
                                    <a href="">International</a>
                                    <a href="">Economics</a>
                                    <a href="">Politics</a>
                                    <a href="">Lifestyle</a>
                                    <a href="">Technology</a>
                                    <a href="">Trades</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Single News End-->        
{% endblock %}    