account/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from blogs import settings
from account import views as account_views
from account import forms as account_forms

app_name = 'account'

urlpatterns = [
    
    path('profile/', account_views.profile, name='profile'),
    path('wishlist/', account_views.wishlist_view, name='wishlist'),

    path('register/', account_views.register_view, name='register'),
    path('login/', account_views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='articles:index'), name='logout'),

    path('change-password/',
         auth_views.PasswordChangeView.as_view(
             template_name='account/change-password.html',
             success_url='/',
         ), name='change_password'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password-reset/password_reset.html',
             form_class=account_forms.CustomPasswordResetForm,
             email_template_name='account/password-reset/password_reset_email.html',
             success_url=reverse_lazy('account:password_reset_done',)
         ), name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password-reset/password_reset_done.html'
         ), name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password-reset/password_reset_confirm.html',
             success_url=reverse_lazy('account:password_reset_complete')
         ), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password-reset/password_reset_complete.html',
         ), name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

articles/urls.py
from django.conf.urls.static import static
from blogs import settings
from django.urls import path, include
from articles import views as article_views


app_name = 'articles'
urlpatterns = [
    path('', article_views.IndexPageView.as_view(), name='index'),
    path('category_results/<str:title>/', article_views.category_results.as_view(), name='category_results'),
    path('search', article_views.SearchView.as_view(), name='search_result'),
   
    path('read_more/<str:cate_title>/<str:title>', article_views.details, name='details'),
    path('fave/<str:title>', article_views.favourite_article, name='favourite_article'),
    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
     path('accounts/', include('account.urls')),

]

templates/components/left_slider.html
<div class="col-lg-4">
    <div class="sidebar">
        <div class="sidebar-widget">
            {%if search%}
            <h2 class="sw-title">You may like</h2>
            {%else%}
            <h2 class="sw-title">In This Category</h2>
            {%endif%}
            <div class="news-list">
                {% for article in in_this_category %}
                <div class="nl-item">
                    <div class="nl-img">
                        <img src="/media/{{ article.image }}" />
                    </div>
                    <div class="nl-title">
                        <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{ article.title }}</a>
                    </div>
                </div>
                {%endfor%}
            </div>
        </div>
        
     
        <div class="sidebar-widget">
            <div class="tab-news">
                <ul class="nav nav-pills nav-justified">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="pill" href="#featured">Featured</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="pill" href="#popular">Popular</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="pill" href="#latest">Latest</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="featured" class="container tab-pane active">
                    {% for article in featured %}
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="/media/{{ article.image }}" />
                            </div>
                            <div class="tn-title">
                                <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{ article.title }}</a>
                            </div>
                        </div>
                        {%endfor %}
                    </div>


                    <div id="popular" class="container tab-pane fade">
                        {% for article in most_viewed%}
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="/media/{{ article.image }}" />
                            </div>
                            <div class="tn-title">
                                <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{article.title}}</a>
                            </div>
                        </div>
                       {%endfor%}
                    
                    </div>
                    <div id="latest" class="container tab-pane fade">
                        {% for article in recent%}
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="/media/{{ article.image }}" />
                            </div>
                            <div class="tn-title">
                                <a href="{% url 'articles:details' cate_title=article.category.title  title=article.title  %}">{{article.title}}</a>
                            </div>
                        </div>
                       {%endfor%}
                        
                    </div>
                </div>
            </div>
        </div>
        
       

        <div class="sidebar-widget">
            <h2 class="sw-title">Category List</h2>
            <div class="category">
                {% for title,count in cate_list.items %}
               
                <ul> 
                    <li><a href="{% url 'articles:category_results' title=title  %}">{{title}}</a><span>{{count}}</span></li>
                   
                </ul>
                {%endfor%}
           
            </div>
        </div>

       
        
        <div class="sidebar-widget">
            <h2 class="sw-title">Tags Cloud</h2>
            <div class="tags">
                <a href="">National</a>
                <a href="">International</a>
                <a href="">Economics</a>
                <a href="">Politics</a>
                <a href="">Lifestyle</a>
                <a href="">Technology</a>
                <a href="">Trades</a>
            </div>
        </div>
    </div>
</div>

templates/components/login-register.html
{% load i18n %}
{% load static %}

<!-- Login / Rgister modal-->
<div class="modal fade" id="signin-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <ul class="nav nav-tabs card-header-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" href="#signin-tab" data-toggle="tab" role="tab"
                            aria-selected="true"><i class="czi-unlocked mr-2 mt-n1"></i>Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#signup-tab" data-toggle="tab" role="tab" aria-selected="false"><i
                                class="czi-user mr-2 mt-n1"></i>Sign up</a>
                    </li>
                </ul>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body tab-content py-4">
                <form method="POST" action="{% url 'account:login' %}"
                    class="needs-validation tab-pane fade show active" autocomplete="off" novalidate id="signin-tab">
                    {% csrf_token %}
                    <!-- <div class="form-group">
                        <label for="si-email">Email address</label>
                        <input class="form-control" type="email" id="si-email" placeholder="johndoe@example.com"
                            required />
                        <div class="invalid-feedback">
                            Please provide a valid email address.
                        </div>
                    </div> -->
                    <div class="form-group">
                        <label for="si-email">Username</label>
                        <input class="form-control" type="text" id="si-email" placeholder="johndoe" name="username"
                            required />
                        <div class="invalid-feedback">
                            Please provide a valid email address.
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="si-password">Password</label>
                        <div class="password-toggle">
                            <input class="form-control" type="password" id="si-password" name="password" required />
                            <label class="password-toggle-btn">
                                <input class="custom-control-input" type="checkbox" /><i
                                    class="czi-eye password-toggle-indicator"></i><span class="sr-only">Show
                                    password</span>
                            </label>
                        </div>
                    </div>
                    <div class="form-group d-flex flex-wrap justify-content-between">
                        <div class="custom-control custom-checkbox mb-2">
                        </div>
                        <a class="font-size-sm" href="{% url 'account:password_reset' %}">Forgot password?</a>
                    </div>
                    {% if request.GET.next %}
                    <input type="button" name="next" value="{{ request.Get.next }}">
                    {% endif %}
                    <button class="btn btn-primary btn-block btn-shadow" type="submit">
                        Sign in
                    </button>
                </form>

                <form method="POST" action="{% url 'account:register' %}" class="needs-validation tab-pane fade"
                    autocomplete="off" id="signup-tab">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="su-username">Username</label>
                        <input class="form-control" type="text" id="su-username" placeholder="" name="username"
                            required />
                        <div class="invalid-feedback">Please fill in your Username.</div>
                    </div>
                    <div class="form-group">
                        <label for="su-firstname">First name</label>
                        <input class="form-control" type="text" id="su-firstname" placeholder="John" name="first_name"
                            required />
                        <div class="invalid-feedback">Please fill in your first name.</div>
                    </div>
                    <div class="form-group">
                        <label for="su-lastname">Last name</label>
                        <input class="form-control form-register-name" type="text" id="su-lastname" placeholder="Doe"
                            name="last_name" required />
                        <div class="invalid-feedback">Please fill in your last name.</div>
                    </div>
                    <div class="form-group">
                        <label for="su-email">Email address</label>
                        <input class="form-control" type="email" id="su-email" placeholder="johndoe@example.com"
                            name="email" required />
                        <div class="invalid-feedback">
                            Please provide a valid email address.
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="su-password">Password</label>
                        <div class="password-toggle">
                            <input class="form-control" type="password" id="su-password" name="password1" required />
                            <label class="password-toggle-btn">
                                <input class="custom-control-input" type="checkbox" /><i
                                    class="czi-eye password-toggle-indicator"></i><span class="sr-only">Show
                                    password</span>
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="su-password-confirm">Confirm password</label>
                        <div class="password-toggle">
                            <input class="form-control" type="password" id="su-password-confirm" name="password2"
                                required />
                            <label class="password-toggle-btn">
                                <input class="custom-control-input" type="checkbox" /><i
                                    class="czi-eye password-toggle-indicator"></i><span class="sr-only">Show
                                    password</span>
                            </label>
                        </div>
                    </div>
                    <button class="btn btn-primary btn-block btn-shadow" type="submit">
                        Sign up
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>